
#include<iostream>
using namespace std;
#include<string>

////普通实现页面
////Java页面
//class Java
//{
//public:
//	void  header()
//	{
//		cout << "首页、公开课、登录、注册...（公共资源）" << endl;
//	
//	}
//	void footer()
//	{
//		cout << "帮助中心、交流合作、站内地图...（公共底部）" << endl;
//	}
//	void  left()
//	{
//		cout << "Java、Python、C++...(公共分类列表)" << endl;
//	}
//
//	void content()
//	{
//		cout << "Java学科视频" << endl;
//	}
//};
//
////python的页面
//class Python
//{
//public:
//	void  header()
//	{
//		cout << "首页、公开课、登录、注册...（公共资源）" << endl;
//
//	}
//	void footer()
//	{
//		cout << "帮助中心、交流合作、站内地图...（公共底部）" << endl;
//	}
//	void  left()
//	{
//		cout << "Java、Python、C++...(公共分类列表)" << endl;
//	}
//
//	void content()
//	{
//		cout << "Python学科视频" << endl;
//	}
//};
//
////C++的页面
//class CPP
//{
//public:
//	void  header()
//	{
//		cout << "首页、公开课、登录、注册...（公共资源）" << endl;
//
//	}
//	void footer()
//	{
//		cout << "帮助中心、交流合作、站内地图...（公共底部）" << endl;
//	}
//	void  left()
//	{
//		cout << "Java、Python、C++...(公共分类列表)" << endl;
//	}
//
//	void content()
//	{
//		cout << "CPP学科视频" << endl;
//	}
//};


//继承实现页面
//语法： class 子类 ： 继承方式 父类
//例如：class Java : public BasePage
class BasePage
{
	public:
	void  header()
	{
		cout << "首页、公开课、登录、注册...（公共资源）" << endl;
	
	}
	void footer()
	{
		cout << "帮助中心、交流合作、站内地图...（公共底部）" << endl;
	}
	void  left()
	{
		cout << "Java、Python、C++...(公共分类列表)" << endl;
	}
};
//Jave页面
class Java : public BasePage
{
public:
	void content()
	{
		cout << "Java学科视频" << endl;
	}
};

//Python
class Python : public BasePage
{
public:
	void content()
	{
		cout << "Python学科视频" << endl;
	}
};

//C++
class CPP : public BasePage
{
public:
	void content()
	{
		cout << "CPP的学科视频" << endl;
	}
};
void test01()
{
	cout << "Java的下载视频页面：" << endl;
	Java ja;
	ja.header();
	ja.footer();
	ja.left();
	ja.content();
	cout << "_______________________________" << endl;

	cout << "Python的下载视频页面：" << endl;
	Python py;
	py.header();
	py.footer();
	py.left();
	py.content();

	cout << "_______________________________" << endl;
	cout << "CPP的下载视频页面：" << endl;
	CPP cpp;
	cpp.header();
	cpp.footer();
	cpp.left();
	cpp.content();
}

int main()
{
	test01();

	system("pause");
	return 0;

}
