
#include<iostream>
using namespace std;
#include<string>

////普通实现页面
////Java页面
//class Java
//{
//public:
//	void  header()
//	{
//		cout << "首页、公开课、登录、注册...（公共资源）" << endl;
//	
//	}
//	void footer()
//	{
//		cout << "帮助中心、交流合作、站内地图...（公共底部）" << endl;
//	}
//	void  left()
//	{
//		cout << "Java、Python、C++...(公共分类列表)" << endl;
//	}
//
//	void content()
//	{
//		cout << "Java学科视频" << endl;
//	}
//};
//
////python的页面
//class Python
//{
//public:
//	void  header()
//	{
//		cout << "首页、公开课、登录、注册...（公共资源）" << endl;
//
//	}
//	void footer()
//	{
//		cout << "帮助中心、交流合作、站内地图...（公共底部）" << endl;
//	}
//	void  left()
//	{
//		cout << "Java、Python、C++...(公共分类列表)" << endl;
//	}
//
//	void content()
//	{
//		cout << "Python学科视频" << endl;
//	}
//};
//
////C++的页面
//class CPP
//{
//public:
//	void  header()
//	{
//		cout << "首页、公开课、登录、注册...（公共资源）" << endl;
//
//	}
//	void footer()
//	{
//		cout << "帮助中心、交流合作、站内地图...（公共底部）" << endl;
//	}
//	void  left()
//	{
//		cout << "Java、Python、C++...(公共分类列表)" << endl;
//	}
//
//	void content()
//	{
//		cout << "CPP学科视频" << endl;
//	}
//};


//继承实现页面
//语法： class 子类 ： 继承方式 父类
//例如：class Java : public BasePage
class BasePage
{
	public:
	void  header()
	{
		cout << "首页、公开课、登录、注册...（公共资源）" << endl;
	
	}
	void footer()
	{
		cout << "帮助中心、交流合作、站内地图...（公共底部）" << endl;
	}
	void  left()
	{
		cout << "Java、Python、C++...(公共分类列表)" << endl;
	}
};
//Jave页面
class Java : public BasePage
{
public:
	void content()
	{
		cout << "Java学科视频" << endl;
	}
};

//Python
class Python : public BasePage
{
public:
	void content()
	{
		cout << "Python学科视频" << endl;
	}
};

//C++
class CPP : public BasePage
{
public:
	void content()
	{
		cout << "CPP的学科视频" << endl;
	}
};
void test01()
{
	cout << "Java的下载视频页面：" << endl;
	Java ja;
	ja.header();
	ja.footer();
	ja.left();
	ja.content();
	cout << "_______________________________" << endl;

	cout << "Python的下载视频页面：" << endl;
	Python py;
	py.header();
	py.footer();
	py.left();
	py.content();

	cout << "_______________________________" << endl;
	cout << "CPP的下载视频页面：" << endl;
	CPP cpp;
	cpp.header();
	cpp.footer();
	cpp.left();
	cpp.content();
}

int main()
{
	test01();

	system("pause");
	return 0;

}


继承静态重名方式
#include<iostream>
using namespace std;
#include<string>

class Base
{
public:
	static int m_A;

	static void func()
	{
		cout << "Base-static void func()" << endl;
	}
};
int Base::m_A = 100;

class Son : public Base
{
public:
	static int m_A;
	static void func()
	{
		cout << "Son-static void func()" << endl;
	}
};
int  Son:: m_A=200;

//同门静态成员属性
void test01()
{
	//通过对象访问
	Son s;
	cout << "通过对象访问" << endl;
	cout << "Son m_A=" << s.m_A << endl;
	cout << "Base m_A=" << s.Base::m_A << endl;


	//通过类名访问
	cout << "通过类名访问" << endl;
	cout << "Son m_A= " << Son::m_A << endl;
	cout << "Base m_A= " << Son::Base::m_A << endl;

}
void test02()
{
	//1.通过对象访问
	cout << "通过对象访问" << endl;
	Son s;
	s.func();
	s.Base::func();
  
	//通过类名访问
	cout << "通过类名访问" << endl;
	Son::func();
	Son::Base::func();
}
 
int main()
{
	test01();

	system("pause");
	return 0;

}
